export const DOUYIN_LIVE_HOST = '127.0.0.1';
export const DOUYIN_LIVE_WS_PORT = 1088;
export const DOUYIN_LIVE_HEALTH_POLL_INTERVAL_MS = 200;
export const DOUYIN_LIVE_DEFAULT_STARTUP_TIMEOUT_MS = 15_000;
export const DOUYIN_LIVE_STDIO_BUFFER_LIMIT = 4096;
