export {
  PersonaStore,
  PersonaStoreUnavailableError,
  PersonaNotFoundError,
  PersonaPrincipalConflictError,
  PersonaPrincipalDeletionError,
  PersonaReferencedError,
  AliasNotFoundError,
  AliasDuplicateError,
  PersonaInvalidParamsError,
  PersonaVersionNotFoundError,
  PersonaVersionImmutableError,
  PersonaContentDecryptionError,
} from './PersonaStore.js';
export type { PersonaStoreOptions } from './PersonaStore.js';
export {
  ALIAS_KINDS_V1,
  PERSONA_VERSION_STATUSES,
  type AliasInput,
  type AliasKind,
  type AliasRow,
  type CreateDraftParams,
  type CreatePersonaParams,
  type PersonaSummary,
  type PersonaVersionMeta,
  type PersonaVersionStatus,
  type UpdateAliasParams,
  type UpdatePersonaParams,
  type VersionComparison,
} from './types.js';
